version: '3'

#here we create the volumes. We keep the same names for backup purposes
volumes:
  filebrowser:
    name: filebrowser

#we put all containers under the same network. this is the first stack that needs to be deployed.
networks:
  internal-network:
    driver: bridge
    name: virtual_net
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
 # Homepage - A modern (fully static, fast), secure (fully proxied), highly customizable application dashboard with integrations for more than 25 services and translations for over 15 languages. Easily configured via YAML files (or discovery via docker labels).
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /home/cloud/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
      - /mnt/data:/data #display storage information of your data location
      - /home/cloud:/os #display information of your homepage location folder. usually the local drive
    networks:
      - internal-network
    restart: unless-stopped
  #filebrowser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files.
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    user: "${PUID}:${PGID}"
    ports:
      - 8443:8080
    volumes:
#      - /mnt/data/user-files:/data
      - filebrowser:/config
    environment:
      - FB_BASEURL=/filebrowser
    networks:
      - internal-network
    restart: always
